source 'https://rubygems.org'


gem 'rails', '4.2.6'

gem 'rails-api'

gem 'spring', :group => :development
gem 'rack-cors'
gem 'bcrypt'
gem 'active_model_serializers'
gem 'pg'
gem 'faker'


group :development, :test do
gem 'sqlite3'
gem 'factory_girl_rails'
end
